#Requires -Version 5.1
[CmdletBinding()]
param(
  # Python/Module/Output
  [string]$Py        = ".\.venv\Scripts\python.exe",
  [string]$Module    = "project.runner.cli",
  [string]$OutRoot   = ".\outputs\night",

  # 모드: rule(고정비중 스윕) | hjb(최적정책) | rl(강화학습)
  [ValidateSet("rule","hjb","rl")][string]$Method = "rule",
  [ValidateSet("4pct","cpb","vpw","kgr")][string]$Baseline = "4pct",

  # 공통 실행 설정
  [int]$Seeds        = 5,
  [string]$SeedList  = "",
  [int]$NPaths       = 2000,
  [ValidateSet("iid","bootstrap")][string]$MarketMode = "iid",
  [ValidateSet(0,12,24)][int]$BootstrapBlock = 0,

  [ValidateSet("on","off")][string]$Quiet = "on",
  [ValidateSet("on","off")][string]$XaiOn = "off",

  # ETA
  [ValidateSet("off","history")][string]$EtaMode = "history",
  [string]$EtaBudgetHms = "",
  [int]$EtaBudgetS = 0,
  [ValidateSet("on","off")][string]$EtaHardStop = "off",
  [string]$EtaDb = ".\outputs\_logs\eta_history.csv",

  # 배치/요약
  [switch]$SkipExisting = $true,
  [switch]$DoSummary = $true,

  # RULE 스윕 리스트 (Method=rule 일 때 사용)
  [double[]]$WList = @(0.0,0.3,0.5,0.7,1.0),

  # HJB 단일 평가 기본 파라미터
  [double]$Lambda   = 0.8,
  [double]$Alpha    = 0.95,
  [double]$WMax     = 0.70,
  [double]$QFloor   = 0.02,
  [double]$Fee      = 0.004,
  [int]$HorizonY    = 35,

  [string]$Tag = "",

  # 추가 인자 패스스루
  [string[]]$ExtraArgs = @()
)

# ─────────────────────────────────────────────────────────
# 글로벌 상태
# ─────────────────────────────────────────────────────────
$global:RunPlan   = @()
$global:RunStats  = [ordered]@{ StartedAt = (Get-Date); Total=0; Done=0; Fail=0; Ok=0; Durations=@() }

function Ensure-Dir($p) { if (!(Test-Path $p)){ New-Item -ItemType Directory -Force -Path $p | Out-Null } }

# Python shim (불필요 인자 제거 등)
function Ensure-Shim {
  $shimDir = ".\.scripts"
  Ensure-Dir $shimDir
  $shimPath = Join-Path $shimDir "cli_shim.py"
  @"
# auto-generated by night_run.ps1 (refactor)
import sys, os, runpy

def strip_unknown(argv):
    out, skip = [], 0
    for i, tok in enumerate(argv):
        if skip:
            skip -= 1; continue
        low = str(tok).lower()
        # 과거 옵션 호환성: --dump_eval 제거
        if low in ("--dump_eval","--dump-eval"):
            if i+1 < len(argv) and not str(argv[i+1]).startswith("-"):
                skip = 1
            continue
        out.append(tok)
    return out

if __name__ == "__main__":
    if len(sys.argv) < 2:
        raise SystemExit("usage: cli_shim.py <module> [args...]")
    module = sys.argv[1]
    repo_root = os.path.abspath(os.path.join(os.path.dirname(__file__), os.pardir))
    if repo_root not in sys.path:
        sys.path.insert(0, repo_root)
    sys.argv = [sys.argv[0]] + strip_unknown(sys.argv[2:])
    runpy.run_module(module, run_name="__main__")
"@ | Set-Content -Path $shimPath -Encoding UTF8
  return $shimPath
}

function Add-Run {
  param([string]$Tag,[string]$OutDir,[hashtable]$Fixed=@{})
  $global:RunPlan += [pscustomobject]@{ Tag=$Tag; OutDir=$OutDir; Fixed=$Fixed }
}

function Get-BaseArgs {
  param([string]$OutDir,[string]$Tag,[hashtable]$Fixed)

  $args = @(
    "--method",$Method,
    # ✅ rule일 때 baseline 필수 전달 (중요 버그 픽스)
    $(if($Method -eq "rule"){ @("--baseline",$Baseline) } else { @() }),
    "--market_mode",$MarketMode,
    "--horizon_years","$HorizonY",
    "--alpha","$Alpha",
    "--beta","0.996",
    "--lambda_term","$Lambda",
    "--w_max","$WMax",
    "--q_floor","$QFloor",
    "--phi_adval","$Fee",
    "--outputs",$OutDir,
    "--tag",$Tag,
    "--autosave","on",
    "--quiet",$Quiet,
    "--xai_on",$XaiOn
  )

  if ($MarketMode -eq "bootstrap" -and $BootstrapBlock -in 12,24) {
    $args += @("--bootstrap_block","$BootstrapBlock")
  }

  if ($SeedList -and $SeedList.Trim().Length -gt 0) {
    $args += @("--seeds") + ($SeedList -split ",")
  } else {
    $args += @("--seeds","$Seeds")
  }
  $args += @("--n_paths","$NPaths")

  if ($EtaMode)        { $args += @("--eta_mode",$EtaMode) }
  if ($EtaBudgetHms)   { $args += @("--eta_budget_hms",$EtaBudgetHms) }
  if ($EtaBudgetS -gt 0){ $args += @("--eta_budget_s","$EtaBudgetS") }
  if ($EtaHardStop)    { $args += @("--eta_hard_stop",$EtaHardStop) }
  if ($EtaDb)          { $args += @("--eta_db",$EtaDb) }

  foreach ($k in $Fixed.Keys) {
    $args += @("--$k", "$($Fixed[$k])")
  }
  if ($ExtraArgs.Count -gt 0) { $args += $ExtraArgs }

  return ,$args
}

function Append-DecisionLog {
  param([string]$OutRootLocal,[hashtable]$Row)
  $logDir = Join-Path $OutRootLocal "_logs"
  Ensure-Dir $logDir
  $logCsv = Join-Path $logDir "decision_log.csv"

  $order = @("timestamp","tag","outdir","rc","took_s","took_hms","seeds","seed_list","n_paths","module","commit","version")
  $obj = New-Object psobject
  foreach($k in $order){ $null = Add-Member -InputObject $obj -MemberType NoteProperty -Name $k -Value ($Row[$k]) }

  if (!(Test-Path $logCsv)) {
    $obj | Export-Csv -Path $logCsv -NoTypeInformation -Encoding UTF8
  } else {
    $obj | Export-Csv -Path $logCsv -NoTypeInformation -Append -Encoding UTF8
  }
}

function Print-ETA {
  $done = [double]$global:RunStats.Done
  $total = [double]$global:RunStats.Total
  if ($done -le 0 -or $global:RunStats.Durations.Count -eq 0) { return }
  $avg = ($global:RunStats.Durations | Measure-Object -Average).Average
  $remaining = $total - $done
  $etaSec = [int]([math]::Max(0, $remaining * $avg))
  $eta = (Get-Date).AddSeconds($etaSec)
  Write-Host ("[ETA ] {0}/{1} avg={2}s eta={3}" -f $done, $total, [int]$avg, $eta.ToString("yyyy-MM-dd HH:mm:ss"))
}

function Invoke-Run {
  param([string]$Tag,[string]$OutDir,[hashtable]$Fixed = @{})

  $metricsPath = Join-Path $OutDir "_logs\metrics.csv"
  if ($SkipExisting -and (Test-Path $metricsPath)) {
    Write-Host "[SKIP] $Tag (found: $metricsPath)"
    $global:RunStats.Done++; Print-ETA; return
  }

  Ensure-Dir $OutDir
  $args = Get-BaseArgs -OutDir $OutDir -Tag $Tag -Fixed $Fixed
  $shim = Ensure-Shim

  $sw = [System.Diagnostics.Stopwatch]::StartNew()
  $started = Get-Date
  Write-Host "[RUN ] $Tag -> $OutDir (`$Method=$Method)"

  & $Py $shim $Module @args
  $rc = $LASTEXITCODE
  $sw.Stop()
  $ended = Get-Date

  $global:RunStats.Durations += $sw.Elapsed.TotalSeconds
  $global:RunStats.Done++
  if ($rc -ne 0) {
    $global:RunStats.Fail++
    Write-Host ("[FAIL] {0} rc={1} took={2}" -f $Tag, $rc, $sw.Elapsed.ToString()) -ForegroundColor Red
  } else {
    $global:RunStats.Ok++
    Write-Host ("[DONE] {0} took={1}" -f $Tag, $sw.Elapsed.ToString()) -ForegroundColor Green
  }

  $row = @{
    timestamp = $ended.ToString("s")
    tag       = $Tag
    outdir    = $OutDir
    rc        = $rc
    took_s    = [int]$sw.Elapsed.TotalSeconds
    took_hms  = $sw.Elapsed.ToString()
    seeds     = $Seeds
    seed_list = $SeedList
    n_paths   = $NPaths
    module    = $Module
    commit    = ""
    version   = "night_run.ps1 v6 (rl+baseline+summary fixes)"
  }
  Append-DecisionLog -OutRootLocal $OutRoot -Row $row
  Print-ETA
}

function Build-Plan {
  if ($Method -eq "rule") {
    # RULE: w_fixed 스윕
    $root = Join-Path $OutRoot "w_fixed"
    foreach ($w in $WList) {
      $wLabel = ("w_{0}" -f ($w.ToString().Replace('.','_')))
      $outDir = Join-Path $root $wLabel
      Add-Run -Tag ("rule_w{0}" -f $w) -OutDir $outDir -Fixed @{ "w_fixed" = $w }
    }
  } elseif ($Method -eq "hjb") {
    # HJB: 단일 포인트
    $root = Join-Path $OutRoot "hjb"
    $tag2 = if ($Tag) { $Tag } else { "hjb_base" }
    $outDir = Join-Path $root $tag2
    Add-Run -Tag $tag2 -OutDir $outDir -Fixed @{}
  } elseif ($Method -eq "rl") {
    # RL: 단일 포인트 (하이퍼파라미터는 -ExtraArgs로 전달)
    $root = Join-Path $OutRoot "rl"
    $tag2 = if ($Tag) { $Tag } else { "rl_base" }
    $outDir = Join-Path $root $tag2
    Add-Run -Tag $tag2 -OutDir $outDir -Fixed @{}
  }
}

function Make-Summary {
  param([string]$OutRootLocal)

  $cleanPath  = Join-Path $OutRootLocal "night_summary_clean.csv"
  $reportPath = Join-Path $OutRootLocal "night_summary_report.csv"

  $metrics = Get-ChildItem -Path $OutRootLocal -Recurse -Filter "metrics.csv"
  if ($metrics.Count -eq 0) {
    Write-Warning "metrics.csv 없음 - 먼저 배치를 실행하세요."
    return
  }

  $rows = @()
  foreach ($m in $metrics) {
    try {
      $csv = Import-Csv $m.FullName

      foreach ($r in $csv) {
        $full = $m.DirectoryName

        # 폴더명에서 w_* 추출
        $w_label = ($full -split "[\\\/]") | Where-Object { $_ -like "w_*" } | Select-Object -Last 1
        if (-not $w_label) { $w_label = "NA" }

        # 안전 파싱: method
        $methodVal = ""
        if ($r.PSObject.Properties.Name -contains "method") { $methodVal = [string]$r.method }

        # ✅ HJB/RL은 w_fixed 개념 없음 → 무조건 NA
        if ($methodVal -in @("hjb","rl")) { $w_label = "NA" }

        # ✅ baseline: 규칙 기반이면 반드시 CSV에서 읽는다(구버전 대비)
        $baselineVal = ""
        if ($r.PSObject.Properties.Name -contains "baseline" -and $r.baseline) {
          $baselineVal = [string]$r.baseline
        }

        # seed/elapsed 안전 파싱
        $seedVal = ""
        foreach ($cand in @("seed","seed_id","seed_idx")) {
          if ($r.PSObject.Properties.Name -contains $cand -and $r.$cand) { $seedVal = [string]$r.$cand; break }
        }

        $elapsedVal = ""
        foreach ($cand in @("time_total_hms","elapsed_hms","elapsed")) {
          if ($r.PSObject.Properties.Name -contains $cand -and $r.$cand) { $elapsedVal = [string]$r.$cand; break }
        }

        $rows += [pscustomobject]@{
          tag      = $r.tag
          method   = $methodVal
          baseline = $baselineVal
          w_fixed  = $w_label
          seed     = $seedVal
          EW       = [double]$r.EW
          ES95     = [double]$r.ES95
          RuinPct  = [double]$r.RuinPct
          mean_WT  = [double]$r.mean_WT
          elapsed  = $elapsedVal
          out_dir  = $full
        }
      }
    } catch {
      Write-Warning "Import 실패: $($m.FullName)  $_"
    }
  }

  # ✅ 중복 제거: 같은 (tag,method,baseline,w_fixed,seed) 기준
  $rows =
    $rows |
    Sort-Object tag,method,baseline,w_fixed,seed -Unique

  $rows | Export-Csv -NoTypeInformation -Encoding UTF8 $cleanPath
  Write-Host "  -> $cleanPath"

  $report =
    $rows |
    Group-Object method, baseline, w_fixed |
    ForEach-Object {
      $g = $_.Group
      [pscustomobject]@{
        method   = $g[0].method
        baseline = $g[0].baseline
        w_fixed  = $g[0].w_fixed
        seed_n   = $g.Count
        EW_avg   = [double]("{0:N6}" -f (($g | Measure-Object -Property EW      -Average).Average))
        ES95_avg = [double]("{0:N6}" -f (($g | Measure-Object -Property ES95    -Average).Average))
        Ruin_avg = [double]("{0:N6}" -f (($g | Measure-Object -Property RuinPct -Average).Average))
        WT_avg   = [double]("{0:N6}" -f (($g | Measure-Object -Property mean_WT -Average).Average))
      }
    } | Sort-Object method, baseline, w_fixed

  $report | Export-Csv -NoTypeInformation -Encoding UTF8 $reportPath
  Write-Host "  -> $reportPath"
}

# ─────────────────────────────────────────────────────────
# PLAN
# ─────────────────────────────────────────────────────────
Build-Plan
$global:RunStats.Total = $global:RunPlan.Count
Write-Host ("[PLAN] total runs = {0} (Method={1})" -f $global:RunStats.Total, $Method)

# ─────────────────────────────────────────────────────────
# RUN
# ─────────────────────────────────────────────────────────
foreach ($job in $global:RunPlan) {
  Invoke-Run -Tag $job.Tag -OutDir $job.OutDir -Fixed $job.Fixed
}

Write-Host ("[SUMM] Ok={0} Fail={1} Done={2}/{3} (started {4})" -f `
  $global:RunStats.Ok, $global:RunStats.Fail, $global:RunStats.Done, $global:RunStats.Total, `
  $global:RunStats.StartedAt.ToString("yyyy-MM-dd HH:mm:ss"))

# ─────────────────────────────────────────────────────────
# SUMMARY
# ─────────────────────────────────────────────────────────
if ($DoSummary) {
  Write-Host ">> 요약집계 생성 시작"
  Make-Summary -OutRootLocal $OutRoot
  Write-Host ">> 요약집계 완료"
}
