#Requires -Version 5.1
[CmdletBinding()]
param(
  [string]$Py        = ".\.venv\Scripts\python.exe",
  [string]$Module    = "project.runner.cli",
  [string]$OutRoot   = ".\outputs\night",

  [int]$Seeds        = 5,
  [string]$SeedList  = "",

  [int]$NPaths       = 2000,
  [int]$BootstrapBlock = 0,
  [ValidateSet("on","off")][string]$Quiet = "on",
  [ValidateSet("on","off")][string]$XaiOn = "off",

  # ETA
  [ValidateSet("off","history")][string]$EtaMode = "history",
  [string]$EtaBudgetHms = "",
  [int]$EtaBudgetS = 0,
  [ValidateSet("on","off")][string]$EtaHardStop = "off",
  [string]$EtaDb = ".\outputs\_logs\eta_history.csv",

  [switch]$SkipExisting = $true,
  [string[]]$ExtraArgs = @()
)

$global:RunPlan   = @()
$global:RunStats  = [ordered]@{ StartedAt = (Get-Date); Total=0; Done=0; Fail=0; Ok=0; Durations=@() }

function Ensure-Dir($p) { if (!(Test-Path $p)){ New-Item -ItemType Directory -Force -Path $p | Out-Null } }

# ── NEW: Python shim 생성 (dump_eval 제거)
function Ensure-Shim {
  $shimDir = ".\.scripts"
  Ensure-Dir $shimDir
  $shimPath = Join-Path $shimDir "cli_shim.py"
  @"
# auto-generated by night_run.ps1
import sys, os, runpy

def strip_unknown(argv):
    out = []
    skip = 0
    for i, tok in enumerate(argv):
        if skip:
            skip -= 1
            continue
        low = str(tok).lower()
        if low in ("--dump_eval", "--dump-eval"):
            if i + 1 < len(argv) and not str(argv[i+1]).startswith("-"):
                skip = 1
            continue
        out.append(tok)
    return out

if __name__ == "__main__":
    if len(sys.argv) < 2:
        raise SystemExit("usage: cli_shim.py <module> [args...]")
    module = sys.argv[1]
    # 레포 루트(.scripts의 부모)를 sys.path 맨 앞에 추가
    repo_root = os.path.abspath(os.path.join(os.path.dirname(__file__), os.pardir))
    if repo_root not in sys.path:
        sys.path.insert(0, repo_root)
    # 남은 인자 가공
    sys.argv = [sys.argv[0]] + strip_unknown(sys.argv[2:])
    runpy.run_module(module, run_name="__main__")
"@ | Set-Content -Path $shimPath -Encoding UTF8
  return $shimPath
}

function Add-Run {
  param([string]$Tag,[string]$OutDir,[hashtable]$Fixed=@{})
  $global:RunPlan += [pscustomobject]@{ Tag=$Tag; OutDir=$OutDir; Fixed=$Fixed }
}

function Get-BaseArgs {
  param([string]$OutDir,[string]$Tag,[hashtable]$Fixed)

  $args = @(
    "--method","hjb",
    "--market_mode","iid",
    "--horizon_years","35",
    "--alpha","0.95",
    "--beta","0.996",
    "--lambda_term","0.8",
    "--w_max","0.70",
    "--q_floor","0.02",
    "--phi_adval","0.004",
    "--outputs",$OutDir,
    "--tag",$Tag,
    "--autosave","on",
    "--quiet",$Quiet,
    "--xai_on",$XaiOn
  )

  if ($BootstrapBlock -ne $null) { $args += @("--bootstrap_block","$BootstrapBlock") }

  if ($SeedList -and $SeedList.Trim().Length -gt 0) {
    $args += @("--seeds") + ($SeedList -split ",")
  } else {
    $args += @("--seeds","$Seeds")
  }

  $args += @("--n_paths","$NPaths")

  if ($EtaMode)        { $args += @("--eta_mode",$EtaMode) }
  if ($EtaBudgetHms)   { $args += @("--eta_budget_hms",$EtaBudgetHms) }
  if ($EtaBudgetS -gt 0){ $args += @("--eta_budget_s","$EtaBudgetS") }
  if ($EtaHardStop)    { $args += @("--eta_hard_stop",$EtaHardStop) }
  if ($EtaDb)          { $args += @("--eta_db",$EtaDb) }

  foreach ($k in $Fixed.Keys) {
    $args += @("--$k", "$($Fixed[$k])")
  }

  if ($ExtraArgs.Count -gt 0) { $args += $ExtraArgs }

  return ,$args
}

function Append-DecisionLog {
  param([string]$OutRootLocal,[hashtable]$Row)
  $logDir = Join-Path $OutRootLocal "_logs"
  Ensure-Dir $logDir
  $logCsv = Join-Path $logDir "decision_log.csv"

  $order = @("timestamp","tag","outdir","rc","took_s","took_hms","seeds","seed_list","n_paths","module","commit","version")
  $obj = New-Object psobject
  foreach($k in $order){ $null = Add-Member -InputObject $obj -MemberType NoteProperty -Name $k -Value ($Row[$k]) }

  if (!(Test-Path $logCsv)) {
    $obj | Export-Csv -Path $logCsv -NoTypeInformation -Encoding UTF8
  } else {
    $obj | Export-Csv -Path $logCsv -NoTypeInformation -Append -Encoding UTF8
  }
}

function Print-ETA {
  $done = [double]$global:RunStats.Done
  $total = [double]$global:RunStats.Total
  if ($done -le 0 -or $global:RunStats.Durations.Count -eq 0) { return }
  $avg = ($global:RunStats.Durations | Measure-Object -Average).Average
  $remaining = $total - $done
  $etaSec = [int]([math]::Max(0, $remaining * $avg))
  $eta = (Get-Date).AddSeconds($etaSec)
  Write-Host ("[ETA ] {0}/{1} avg={2}s eta={3}" -f $done, $total, [int]$avg, $eta.ToString("yyyy-MM-dd HH:mm:ss"))
}

function Invoke-Run {
  param([string]$Tag,[string]$OutDir,[hashtable]$Fixed = @{})

  $metricsPath = Join-Path $OutDir "_logs\metrics.csv"
  if ($SkipExisting -and (Test-Path $metricsPath)) {
    Write-Host "[SKIP] $Tag (found: $metricsPath)"
    $global:RunStats.Done++; Print-ETA; return
  }

  Ensure-Dir $OutDir

  $args = Get-BaseArgs -OutDir $OutDir -Tag $Tag -Fixed $Fixed
  $shim = Ensure-Shim
  $sw = [System.Diagnostics.Stopwatch]::StartNew()
  $started = Get-Date
  Write-Host "[RUN ] $Tag -> $OutDir"

  # shim 파일을 직접 실행 (모듈 -m 사용 안함)
  & $Py $shim $Module @args

  $rc = $LASTEXITCODE
  $sw.Stop()
  $ended = Get-Date

  $global:RunStats.Durations += $sw.Elapsed.TotalSeconds
  $global:RunStats.Done++
  if ($rc -ne 0) {
    $global:RunStats.Fail++
    Write-Host ("[FAIL] {0} rc={1} took={2}" -f $Tag, $rc, $sw.Elapsed.ToString()) -ForegroundColor Red
  } else {
    $global:RunStats.Ok++
    Write-Host ("[DONE] {0} took={1}" -f $Tag, $sw.Elapsed.ToString()) -ForegroundColor Green
  }

  $row = @{
    timestamp = $ended.ToString("s")
    tag       = $Tag
    outdir    = $OutDir
    rc        = $rc
    took_s    = [int]$sw.Elapsed.TotalSeconds
    took_hms  = $sw.Elapsed.ToString()
    seeds     = $Seeds
    seed_list = $SeedList
    n_paths   = $NPaths
    module    = $Module
    commit    = ""
    version   = "night_run.ps1 v4 (shim)"
  }
  Append-DecisionLog -OutRootLocal $OutRoot -Row $row
  Print-ETA
}

# ─────────────────────────────────────────────────────────
# 1) 플랜
# ─────────────────────────────────────────────────────────
$wLevels = @(0.0, 0.3, 0.5, 0.7, 1.0)
foreach ($w in $wLevels) {
  $outDir = Join-Path $OutRoot ("w_fixed\w_{0}" -f ($w -replace '\.','_'))
  Add-Run -Tag ("wfixed_{0}" -f $w) -OutDir $outDir -Fixed @{ "w_fixed" = $w }
}

$global:RunStats.Total = $global:RunPlan.Count
Write-Host ("[PLAN] total runs = {0}" -f $global:RunStats.Total)

# ─────────────────────────────────────────────────────────
# 2) 실행
# ─────────────────────────────────────────────────────────
foreach ($job in $global:RunPlan) {
  Invoke-Run -Tag $job.Tag -OutDir $job.OutDir -Fixed $job.Fixed
}

Write-Host ("[SUMM] Ok={0} Fail={1} Done={2}/{3} (started {4})" -f `
  $global:RunStats.Ok, $global:RunStats.Fail, $global:RunStats.Done, $global:RunStats.Total, `
  $global:RunStats.StartedAt.ToString("yyyy-MM-dd HH:mm:ss"))
