#Requires -Version 5.1
[CmdletBinding()]
param(
  # Python/Module/Output
  [string]$Py        = ".\.venv\Scripts\python.exe",
  [string]$Module    = "project.runner.cli",      # shim에서 실패 시 runner.cli로 자동 폴백
  [string]$OutRoot   = ".\outputs\night",

  # 모드: rule(고정비중 스윕) | hjb(최적정책) | rl(강화학습)
  [ValidateSet("rule","hjb","rl")][string]$Method = "rule",
  [ValidateSet("4pct","cpb","vpw","kgr")][string]$Baseline = "4pct",

  # 공통 실행 설정
  [int]$Seeds        = 5,
  [string]$SeedList  = "",
  [int]$NPaths       = 2000,
  [ValidateSet("iid","bootstrap")][string]$MarketMode = "iid",
  [ValidateSet(0,12,24)][int]$BootstrapBlock = 0,

  [ValidateSet("on","off")][string]$Quiet = "on",
  [ValidateSet("on","off")][string]$XaiOn = "off",

  # ETA
  [ValidateSet("off","history")][string]$EtaMode = "history",
  [string]$EtaBudgetHms = "",
  [int]$EtaBudgetS = 0,
  [ValidateSet("on","off")][string]$EtaHardStop = "off",
  [string]$EtaDb = ".\outputs\_logs\eta_history.csv",

  # 배치/요약
  [switch]$SkipExisting = $true,
  [switch]$DoSummary = $true,

  # RULE 스윕 리스트 (Method=rule 일 때 사용)
  [double[]]$WList = @(0.0,0.3,0.5,0.7,1.0),

  # HJB 단일 평가 기본 파라미터
  [double]$Lambda   = 0.8,
  [double]$Alpha    = 0.95,
  [double]$WMax     = 0.70,
  [double]$QFloor   = 0.02,
  [double]$Fee      = 0.004,
  [int]$HorizonY    = 35,

  [string]$Tag = "",

  # 추가 인자 패스스루
  [string[]]$ExtraArgs = @()
)

Set-StrictMode -Version Latest
$ErrorActionPreference = "Stop"
# ─────────────────────────────────────────────────────────
# 유틸
# ─────────────────────────────────────────────────────────
function Ensure-Dir($p) { if (!(Test-Path $p)){ New-Item -ItemType Directory -Force -Path $p | Out-Null } }

function Resolve-AbsPath([string]$p) {
  if ([string]::IsNullOrWhiteSpace($p)) { return $p }
  $rp = Resolve-Path -Path $p -ErrorAction SilentlyContinue
  if ($rp) { return $rp.Path }
  return (Join-Path (Get-Location) $p)
}

function Ensure-Python {
  $pyAbs = Resolve-AbsPath $Py
  if (-not (Test-Path $pyAbs)) { throw "Python not found: $pyAbs" }
  return $pyAbs
}

function Warn-If($cond,$msg){ if($cond){ Write-Warning $msg } }

# 안전한 double 캐스팅
function To-DoubleOrNull($v){
  if ($null -eq $v) { return $null }
  $s = "$v".Trim()
  if ($s.Length -eq 0) { return $null }
  [double]$out = 0.0
  if ([double]::TryParse($s, [System.Globalization.NumberStyles]::Any,
      [System.Globalization.CultureInfo]::InvariantCulture, [ref]$out)) {
    return $out
  }
  return $null
}

# Python shim 생성 (모듈 진입 + 폴백)
function Ensure-Shim {
  $shimDir = ".\.scripts"
  Ensure-Dir $shimDir
  $shimPath = Join-Path $shimDir "cli_shim.py"
  @"
# auto-generated by night_run.ps1 (refactor v9)
import sys, os, runpy

DROP_OPTS = {"--dump_eval", "--dump-eval"}

def strip_unknown(argv):
    out, skip = [], 0
    for i, tok in enumerate(argv):
        if skip:
            skip -= 1; continue
        low = str(tok).lower()
        if low in DROP_OPTS:
            if i+1 < len(argv) and not str(argv[i+1]).startswith("-"):
                skip = 1
            continue
        out.append(tok)
    return out

def try_run(module):
    try:
        runpy.run_module(module, run_name="__main__")
        return True
    except ModuleNotFoundError as e:
        sys.stderr.write(f"[shim] ModuleNotFoundError: {e}\\n")
        return False

if __name__ == "__main__":
    if len(sys.argv) < 2:
        raise SystemExit("usage: cli_shim.py <module> [args...]")
    module = sys.argv[1]
    repo_root = os.path.abspath(os.path.join(os.path.dirname(__file__), os.pardir))
    if repo_root not in sys.path:
        sys.path.insert(0, repo_root)
    sys.argv = [sys.argv[0]] + strip_unknown(sys.argv[2:])
    if not try_run(module):
        # fallback 모듈명 (runner.cli)
        fb = "runner.cli"
        sys.stderr.write(f"[shim] fallback to {fb}\\n")
        try_run(fb)
"@ | Set-Content -Path $shimPath -Encoding UTF8
  return (Resolve-AbsPath $shimPath)
}

# ─────────────────────────────────────────────────────────
# 전역 상태
# ─────────────────────────────────────────────────────────
$global:RunPlan   = @()
$global:RunStats  = [ordered]@{ StartedAt = (Get-Date); Total=0; Done=0; Fail=0; Ok=0; Durations=@() }

function Append-DecisionLog {
  param([string]$OutRootLocal,[hashtable]$Row)
  $logDir = Join-Path $OutRootLocal "_logs"
  Ensure-Dir $logDir
  $logCsv = Join-Path $logDir "decision_log.csv"

  $order = @("timestamp","method","tag","outdir","rc","took_s","took_hms",
             "seeds","seed_list","n_paths","module","commit","version")
  $obj = New-Object psobject
  foreach($k in $order){ $null = Add-Member -InputObject $obj -MemberType NoteProperty -Name $k -Value ($Row[$k]) }

  if (!(Test-Path $logCsv)) {
    $obj | Export-Csv -Path $logCsv -NoTypeInformation -Encoding UTF8
  } else {
    $obj | Export-Csv -Path $logCsv -NoTypeInformation -Append -Encoding UTF8
  }
}

function Print-ETA {
  $done = [double]$global:RunStats.Done
  $total = [double]$global:RunStats.Total
  if ($done -le 0 -or $global:RunStats.Durations.Count -eq 0) { return }
  $avg = ($global:RunStats.Durations | Measure-Object -Average).Average
  $remaining = $total - $done
  $etaSec = [int]([math]::Max(0, $remaining * $avg))
  $eta = (Get-Date).AddSeconds($etaSec)
  Write-Host ("[ETA ] {0}/{1} avg={2}s eta={3}" -f $done, $total, [int]$avg, $eta.ToString("yyyy-MM-dd HH:mm:ss"))
}

# ─────────────────────────────────────────────────────────
# Validate 입력 조합/환경
# ─────────────────────────────────────────────────────────
function Validate-Inputs {
  $pyAbs = Ensure-Python

  # OutRoot 절대경로 고정(결정성)
  $script:OutRoot = Resolve-AbsPath $OutRoot
  Ensure-Dir $script:OutRoot

  # 조합 검증
  if ($Method -eq "rule") {
    if (-not $WList -or $WList.Count -eq 0) { throw "Method=rule requires non-empty -WList." }
    $WList = @([double[]]($WList | Sort-Object -Unique))
  } else {
    Warn-If ($Baseline -ne "4pct") "Baseline '$Baseline' is ignored when Method=$Method."
  }

  if ($MarketMode -eq "bootstrap") {
    Warn-If ($BootstrapBlock -eq 0) "MarketMode=bootstrap but BootstrapBlock=0 (set 12 or 24)."
    $hasCsv = ($ExtraArgs | Where-Object { $_ -match '^--market_csv$' }).Count -gt 0
    Warn-If (-not $hasCsv) "bootstrap runs usually need --market_csv <path> in -ExtraArgs."
  }

  # Seeds vs SeedList
  if ($SeedList -and $SeedList.Trim().Length -gt 0) {
    $tmp = $SeedList -split "," | Where-Object { $_ -match '^\s*\d+\s*$' } | ForEach-Object { [int]$_ }
    if ($tmp.Count -eq 0) { throw "Invalid -SeedList. Use comma-separated integers." }
  } else {
    if ($Seeds -le 0) { throw "-Seeds must be positive." }
  }

  if ([string]::IsNullOrWhiteSpace($Module)) { throw "Module name is empty." }

  Write-Host ("[CONF] Py={0} Module={1} OutRoot={2}" -f $pyAbs, $Module, $script:OutRoot)
}

# ─────────────────────────────────────────────────────────
# 인자 구성
# ─────────────────────────────────────────────────────────
function Get-BaseArgs {
  param([string]$OutDir,[string]$Tag,[hashtable]$Fixed)

  $args = @(
    "--method",$Method,
    $(if($Method -eq "rule"){ @("--baseline",$Baseline) } else { @() }),
    "--market_mode",$MarketMode,
    "--horizon_years","$HorizonY",
    "--alpha","$Alpha",
    "--beta","0.996",
    "--lambda_term","$Lambda",
    "--w_max","$WMax",
    "--q_floor","$QFloor",
    "--phi_adval","$Fee",
    "--outputs",$OutDir,
    "--tag",$Tag,
    "--autosave","on",
    "--quiet",$Quiet,
    "--xai_on",$XaiOn
  )

  if ($MarketMode -eq "bootstrap" -and $BootstrapBlock -in 12,24) {
    $args += @("--bootstrap_block","$BootstrapBlock")
  }

  if ($SeedList -and $SeedList.Trim().Length -gt 0) {
    $args += @("--seeds") + ($SeedList -split ",")
  } else {
    $args += @("--seeds","$Seeds")
  }
  $args += @("--n_paths","$NPaths")

  if ($EtaMode)        { $args += @("--eta_mode",$EtaMode) }
  if ($EtaBudgetHms)   { $args += @("--eta_budget_hms",$EtaBudgetHms) }
  if ($EtaBudgetS -gt 0){ $args += @("--eta_budget_s","$EtaBudgetS") }
  if ($EtaHardStop)    { $args += @("--eta_hard_stop",$EtaHardStop) }
  if ($EtaDb)          { $args += @("--eta_db",$EtaDb) }

  foreach ($k in $Fixed.Keys) { $args += @("--$k", "$($Fixed[$k])") }
  if ($ExtraArgs.Count -gt 0) { $args += $ExtraArgs }

  return ,$args
}

# ─────────────────────────────────────────────────────────
# 실행
# ─────────────────────────────────────────────────────────
function Invoke-Run {
  param([string]$Tag,[string]$OutDir,[hashtable]$Fixed = @{})

  $metricsPath = Join-Path $OutDir "_logs\metrics.csv"
  if ($SkipExisting -and (Test-Path $metricsPath)) {
    Write-Host "[SKIP] $Tag (found: $metricsPath)"
    $global:RunStats.Done++; Print-ETA; return
  }

  Ensure-Dir $OutDir
  $args = Get-BaseArgs -OutDir $OutDir -Tag $Tag -Fixed $Fixed
  $shim = Ensure-Shim
  $pyAbs = Ensure-Python

  $sw = [System.Diagnostics.Stopwatch]::StartNew()
  $started = Get-Date
  Write-Host "[RUN ] $Tag -> $OutDir (`$Method=$Method)"

  # 안전 실행: ProcessStartInfo
  $argList = @($shim, $Module) + $args
  $quoted = $argList | ForEach-Object {
    if ($_ -is [string] -and $_.Contains(' ')) { '"' + $_ + '"' } else { $_ }
  }
  $psi = New-Object System.Diagnostics.ProcessStartInfo
  $psi.FileName = $pyAbs
  $psi.Arguments = ($quoted -join ' ')
  $psi.RedirectStandardOutput = $false
  $psi.RedirectStandardError  = $false
  $psi.UseShellExecute = $true

  $rc = 1
  try {
    $proc = [System.Diagnostics.Process]::Start($psi)
    $proc.WaitForExit()
    $rc = [int]$proc.ExitCode
  } catch {
    Write-Host "[ERR ] failed to start python: $($_.Exception.Message)" -ForegroundColor Red
    $rc = 1
  }

  $sw.Stop()
  $ended = Get-Date

  $global:RunStats.Durations += $sw.Elapsed.TotalSeconds
  $global:RunStats.Done++
  if ($rc -ne 0) {
    $global:RunStats.Fail++
    Write-Host ("[FAIL] {0} rc={1} took={2}" -f $Tag, $rc, $sw.Elapsed.ToString()) -ForegroundColor Red
  } else {
    $global:RunStats.Ok++
    Write-Host ("[DONE] {0} took={1}" -f $Tag, $sw.Elapsed.ToString()) -ForegroundColor Green
  }

  $row = @{
    timestamp = $ended.ToString("s")
    method    = $Method
    tag       = $Tag
    outdir    = $OutDir
    rc        = $rc
    took_s    = [int]$sw.Elapsed.TotalSeconds
    took_hms  = $sw.Elapsed.ToString()
    seeds     = $Seeds
    seed_list = $SeedList
    n_paths   = $NPaths
    module    = $Module
    commit    = ""   # version_info 유틸 도입 시 채움
    version   = "night_run.ps1 v9 (shim fallback+summary safe-cast+plan dedup)"
  }
  Append-DecisionLog -OutRootLocal $script:OutRoot -Row $row
  Print-ETA
}

# ─────────────────────────────────────────────────────────
# PLAN (단일 경로로 정리)
# ─────────────────────────────────────────────────────────
function Add-Run {
  param([string]$Tag,[string]$OutDir,[hashtable]$Fixed=@{})
  $global:RunPlan += [pscustomobject]@{ Tag=$Tag; OutDir=$OutDir; Fixed=$Fixed }
}

# ─────────────────────────────────────────────────────────
# SUMMARY
# ─────────────────────────────────────────────────────────
function Make-Summary {
  param([string]$OutRootLocal)

  function Get-Col {
    param($r, [string[]]$names)
    foreach ($n in $names) {
      if ($r.PSObject.Properties.Name -contains $n -and $r.$n -ne $null -and "$($r.$n)".Length -gt 0) {
        return $r.$n
      }
    }
    return $null
  }

  function Infer-BaselineFromTag([string]$tag) {
    if (-not $tag) { return "" }
    $m = [regex]::Match($tag, '(4pct|cpb|vpw|kgr)', 'IgnoreCase')
    if ($m.Success) { return $m.Groups[1].Value.ToLower() }
    return ""
  }

  $cleanPath  = Join-Path $OutRootLocal "night_summary_clean.csv"
  $reportPath = Join-Path $OutRootLocal "night_summary_report.csv"

  $metrics = Get-ChildItem -Path $OutRootLocal -Recurse -Filter "metrics.csv"
  if ($metrics.Count -eq 0) { Write-Warning "metrics.csv 없음 - 먼저 배치를 실행하세요."; return }

  $rows = @()
  foreach ($m in $metrics) {
    try {
      $csv = Import-Csv $m.FullName
      foreach ($r in $csv) {
        $full = $m.DirectoryName

        # w_fixed 라벨 (폴더명에서 추출, 없으면 NA)
        $w_label = ($full -split "[\\\/]") | Where-Object { $_ -like "w_*" } | Select-Object -Last 1
        if (-not $w_label) { $w_label = "NA" }

        # method
        $methodVal = ""; if ($r.PSObject.Properties.Name -contains "method") { $methodVal = [string]$r.method }
        if ($methodVal -in @("hjb","rl")) { $w_label = "NA" }

        # baseline: CSV 없으면 tag에서 유추
        $baselineCsv = ""; if ($r.PSObject.Properties.Name -contains "baseline" -and $r.baseline) { $baselineCsv = [string]$r.baseline }
        $tagVal = Get-Col $r @("tag")
        $baselineVal = if ($baselineCsv) { $baselineCsv } else { Infer-BaselineFromTag ($tagVal) }

        # seed/elapsed
        $seedVal = ""; foreach ($cand in @("seed","seed_id","seed_idx")) {
          if ($r.PSObject.Properties.Name -contains $cand -and $r.$cand) { $seedVal = [string]$r.$cand; break }
        }
        $elapsedVal = ""; foreach ($cand in @("time_total_hms","elapsed_hms","elapsed")) {
          if ($r.PSObject.Properties.Name -contains $cand -and $r.$cand) { $elapsedVal = [string]$r.$cand; break }
        }

        # 값 폴백: EW / ES95 / Ruin / mean_WT (안전 캐스팅)
        $EWv    = To-DoubleOrNull (Get-Col $r @("EW","mean_WT"))
        $ES95v  = To-DoubleOrNull (Get-Col $r @("ES95","ES95_loss"))
        $Ruinv  = To-DoubleOrNull (Get-Col $r @("Ruin","RuinPct"))
        $WTv    = To-DoubleOrNull (Get-Col $r @("mean_WT","EW"))

        $rows += [pscustomobject]@{
          tag      = $tagVal
          method   = $methodVal
          baseline = $baselineVal
          w_fixed  = $w_label
          seed     = $seedVal
          EW       = $EWv
          ES95     = $ES95v
          RuinPct  = $Ruinv
          mean_WT  = $WTv
          elapsed  = $elapsedVal
          out_dir  = $full

          # 추가 필드(있으면 반영)
          es_mode        = Get-Col $r @("es_mode")
          AlivePathRate  = Get-Col $r @("AlivePathRate")
          C_ES95_avg     = Get-Col $r @("C_ES95_avg")
          p10_c_last     = Get-Col $r @("p10_c_last")
          p50_c_last     = Get-Col $r @("p50_c_last")
          p90_c_last     = Get-Col $r @("p90_c_last")
        }
      }
    } catch {
      Write-Warning "Import 실패: $($m.FullName)  $_"
    }
  }

  # 결정성 정렬 + 중복 제거
  $rows = $rows | Sort-Object tag,method,baseline,w_fixed,seed,out_dir -Unique
  $rows | Export-Csv -NoTypeInformation -Encoding UTF8 $cleanPath
  Write-Host "  -> $cleanPath"

  $report =
    $rows |
    Group-Object method, baseline, w_fixed |
    ForEach-Object {
      $g = $_.Group
      # 평균 시 Null 제외
      $EW_vals   = $g | Where-Object { $_.EW      -ne $null } | Select-Object -ExpandProperty EW
      $ES95_vals = $g | Where-Object { $_.ES95    -ne $null } | Select-Object -ExpandProperty ES95
      $Ruin_vals = $g | Where-Object { $_.RuinPct -ne $null } | Select-Object -ExpandProperty RuinPct
      $WT_vals   = $g | Where-Object { $_.mean_WT -ne $null } | Select-Object -ExpandProperty mean_WT

      [pscustomobject]@{
        method   = $g[0].method
        baseline = $g[0].baseline
        w_fixed  = $g[0].w_fixed
        seed_n   = $g.Count
        EW_avg   = if($EW_vals){ [double]("{0:N6}" -f ((($EW_vals | Measure-Object -Average).Average))) } else { $null }
        ES95_avg = if($ES95_vals){ [double]("{0:N6}" -f ((($ES95_vals | Measure-Object -Average).Average))) } else { $null }
        Ruin_avg = if($Ruin_vals){ [double]("{0:N6}" -f ((($Ruin_vals | Measure-Object -Average).Average))) } else { $null }
        WT_avg   = if($WT_vals){ [double]("{0:N6}" -f ((($WT_vals | Measure-Object -Average).Average))) } else { $null }
      }
    } | Sort-Object method, baseline, w_fixed

  $report | Export-Csv -NoTypeInformation -Encoding UTF8 $reportPath
  Write-Host "  -> $reportPath"
}

# ─────────────────────────────────────────────────────────
# MAIN (단일 빌드 경로)
# ─────────────────────────────────────────────────────────
Validate-Inputs

function Build-And-Run {
  $global:RunPlan = @()
  if ($Method -eq "rule") {
    $root = Join-Path $script:OutRoot "w_fixed"
    foreach ($w in $WList) {
      $wLabel = ("w_{0}" -f ($w.ToString().Replace('.','_')))
      $outDir = Join-Path $root $wLabel
      Add-Run -Tag ("rule_w{0}" -f $w) -OutDir $outDir -Fixed @{ "w_fixed" = $w }
    }
  } elseif ($Method -eq "hjb") {
    $root = Join-Path $script:OutRoot "hjb"
    $tag2 = if ($Tag) { $Tag } else { "hjb_base" }
    $outDir = Join-Path $root $tag2
    Add-Run -Tag $tag2 -OutDir $outDir -Fixed @{}
  } else {
    $root = Join-Path $script:OutRoot "rl"
    $tag2 = if ($Tag) { $Tag } else { "rl_base" }
    $outDir = Join-Path $root $tag2
    Add-Run -Tag $tag2 -OutDir $outDir -Fixed @{}
  }

  $global:RunStats.Total = $global:RunPlan.Count
  Write-Host ("[PLAN] total runs = {0} (Method={1})" -f $global:RunStats.Total, $Method)

  foreach ($job in $global:RunPlan) {
    Invoke-Run -Tag $job.Tag -OutDir $job.OutDir -Fixed $job.Fixed
  }

  Write-Host ("[SUMM] Ok={0} Fail={1} Done={2}/{3} (started {4})" -f `
    $global:RunStats.Ok, $global:RunStats.Fail, $global:RunStats.Done, $global:RunStats.Total, `
    $global:RunStats.StartedAt.ToString("yyyy-MM-dd HH:mm:ss"))
}

Build-And-Run

if ($DoSummary) {
  Write-Host ">> 요약집계 생성 시작"
  Make-Summary -OutRootLocal $script:OutRoot
  Write-Host ">> 요약집계 완료"
}
