# auto-generated by night_run.ps1 (refactor v11)
import sys, os, runpy
DROP_OPTS = {"--dump_eval", "--dump-eval"}
def strip_unknown(argv):
    out, skip = [], 0
    for i, tok in enumerate(argv):
        if skip: skip -= 1; continue
        low = str(tok).lower()
        if low in DROP_OPTS:
            if i+1 < len(argv) and not str(argv[i+1]).startswith("-"):
                skip = 1
            continue
        out.append(tok)
    return out
def try_run(module):
    try:
        runpy.run_module(module, run_name="__main__"); return True
    except ModuleNotFoundError as e:
        sys.stderr.write(f"[shim] ModuleNotFoundError: {e}\n"); return False
if __name__ == "__main__":
    if len(sys.argv) < 2: raise SystemExit("usage: cli_shim.py <module> [args...]")
    module = sys.argv[1]
    repo_root = os.path.abspath(os.path.join(os.path.dirname(__file__), os.pardir))
    if repo_root not in sys.path: sys.path.insert(0, repo_root)
    sys.argv = [sys.argv[0]] + strip_unknown(sys.argv[2:])
    if not try_run(module):
        fb = "runner.cli"; sys.stderr.write(f"[shim] fallback to {fb}\n"); try_run(fb)
