# auto-generated by night_run.ps1
import sys, os, runpy

def strip_unknown(argv):
    out = []
    skip = 0
    for i, tok in enumerate(argv):
        if skip:
            skip -= 1
            continue
        low = str(tok).lower()
        if low in ("--dump_eval", "--dump-eval"):
            if i + 1 < len(argv) and not str(argv[i+1]).startswith("-"):
                skip = 1
            continue
        out.append(tok)
    return out

if __name__ == "__main__":
    if len(sys.argv) < 2:
        raise SystemExit("usage: cli_shim.py <module> [args...]")
    module = sys.argv[1]
    # ?덊룷 猷⑦듃(.scripts??遺紐?瑜?sys.path 留??욎뿉 異붽?
    repo_root = os.path.abspath(os.path.join(os.path.dirname(__file__), os.pardir))
    if repo_root not in sys.path:
        sys.path.insert(0, repo_root)
    # ?⑥? ?몄옄 媛怨?
    sys.argv = [sys.argv[0]] + strip_unknown(sys.argv[2:])
    runpy.run_module(module, run_name="__main__")
